server:
  port: ${WEATHER_SERVICE_PORT:8085}

spring:
  application:
    name: weather-service
  r2dbc:
    url: ${DATABASE_URL:r2dbc:postgresql://localhost:5432/mi_base}
    username: ${DATABASE_USER:admin}
    password: ${DATABASE_PASSWORD:1234}
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: weather-service-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"

logging:
  level:
    pe.agro.weatherservice: ${LOG_LEVEL:DEBUG}

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html