server:
  port: 8081

spring:
  application:
    name: user-service
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/mi_base
    username: admin
    password: 1234
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: user-service-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      auto-offset-reset: earliest

logging:
  level:
    pe.agro.userservice: DEBUG